debug: true

interact_print_freq: 100
update_print_freq: 1
eval_print_freq: 100

eval_freq: 1
update_steps: 30
plot_freq: 1

data_dir: 'data/stock_data/'
pickle_dir: 'data/pickles/'
log_dir: 'data/logs/'
plot_dir: 'data/plots/'

feat_dim: null
train_len: null
eval_len: null

symbols: null
asset_dim: 128
num_invested: 128
min_volume: 100000

# Training
epochs: 1000
train_ratio: 0.8
batch_size: 32
window_size: 50

# Optimization
embedding_lr: 0.0001
critic_lr: 0.0001
actor_lr: 0.0001
temperature_lr: 0.0003

# Environment
init_cash: 10000
sell_cost: 0.0025
purchase_cost: 0.0025

# DSAC
gamma: 0.99
tau: 0.005
tau_b: 0.005
delay_update: 2
clipping_range: 3
grad_bias: 0.1
std_bias: 0.1

# Experience Replay Buffer
capacity: 180000
perc_last: 0.5

# Actor
min_log_std: -20
max_log_std: 0.5

# LSRE-CANN
depth: 1
num_latents: 16
latent_dim: 64
num_cross_heads: 4
cross_head_dim: 64
num_latent_heads: 4
latent_head_dim: 64
dropout: 0.1